repos:
  - repo: https://github.com/google/yapf
    rev: v0.32.0
    hooks:
      - id: yapf
        additional_dependencies: [toml]
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: end-of-file-fixer
